/*
 Generated by typeshare 1.13.4
*/

/** One operation carried over daemon IPC. */
export type DaemonIpcCall = DaemonIpcCallWire;

/** Validated harness identifier (open set). Serializes as a bare string. */
export type HarnessId = string;

/**
 * One-shot notification target. `Auto` resolves an unqualified CLI value at daemon ingress;
 * explicit variants remove ambiguity without exposing the derived recipient fan-out.
 */
export type NotifyTarget = NotifyTargetWire;

/**
 * A command-envelope request id — a number or a string (the two id forms JSON-RPC allows).
 * `#[serde(untagged)]` so it serializes as a bare `7` or `"abc"` on the wire.
 *
 * `serialized_as` maps the untagged enum to a TS union for the generated mirror — typeshare 1.13
 * cannot infer untagged-enum unions on its own and rejects the bare `i64`. This is a TS-only
 * annotation; the serde wire shape (bare number or bare string) is unchanged.
 */
export type RequestId = RequestIdWire;

/**
 * The send target/verb. `dm`/`post`/`publish` carry their name; `reply` targets the
 * conversation the current injected turn arrived from (no target needed — CLI §4).
 *
 * This is an internally-tagged (`verb`) serde union. typeshare 1.13 cannot emit
 * internally-tagged algebraic enums (it only supports adjacently-tagged), so we map it via
 * `serialized_as` to the hand-authored TS union `SendTargetWire` (appended to the generated
 * mirror by the gen step). TS-only annotation — the serde wire shape is unchanged and the inline
 * round-trip tests assert the internally-tagged JSON.
 */
export type SendTarget = SendTargetWire;

/**
 * The canonical event stream. `#[serde(tag = "type")]` puts the dotted name in a `type` field.
 *
 * This is an internally-tagged (`type`) serde union. typeshare 1.13 cannot emit internally-tagged
 * algebraic enums, so we map it via `serialized_as` to the hand-authored TS union `WsEventWire`
 * (appended to the generated mirror by the gen step). TS-only annotation — the serde wire shape is
 * unchanged and the inline round-trip tests assert the internally-tagged JSON.
 */
export type WsEvent = WsEventWire;

/**
 * Public send acknowledgement. Routing and recipient counts stay internal; callers receive only
 * the durable message identity they can use for reads, receipts, and diagnostics.
 */
export interface Ack {
	messageId: MessageId;
}

/** Per-message ack (DMs). */
export interface AckRequest {
	messageId: MessageId;
}

/** How many in-flight rows moved to `acked`. */
export interface AckResponse {
	acked: number;
}

/** Bulk ack (threads): ack all listed in one call. */
export interface AckThreadsRequest {
	messageIds: MessageId[];
}

/**
 * `nexus admin assign <id> <name>` — a **staged (unnamed)** identity assumes a name whose
 * previous owner died. `id` must be a stable `a_*` agent id or exact
 * `s_*` session id resolving to an identity with **no name yet**; `name` may be free (plain
 * first-naming) or held by an agent that is dead / has no live session or active runtime — that
 * holder is evicted back to unnamed (the staged surface). A name held by a live agent is never
 * takeable. Only the label and future name-addressed traffic transfer; the previous holder's
 * thread memberships, subscriptions, and queued mail stay keyed to its `agent_id`.
 */
export interface AdminAssignRequest {
	/** Staged assignee: stable `a_*` agent id or exact `s_*` session id (never a name). */
	id: string;
	/** The name to assume. */
	name: string;
}

/**
 * Admin assign result. `evicted_agent_id` names the dead previous holder when the name was
 * taken over; `None` means the name was free (plain staged first-naming).
 */
export interface AdminAssignResponse {
	agentId: AgentId;
	sessionId?: SessionId;
	name: string;
	evictedAgentId?: AgentId;
}

/** `nexus admin group assign <group> <name>` — assign a durable agent to a policy group. */
export interface AdminGroupAssignRequest {
	/** Project scope for the group. Defaults to the caller's project. */
	project?: string;
	/** Project-scoped group name. */
	group: string;
	/** Stable target agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	/** Public agent name to assign, or fallback when `agent_id` is omitted. */
	name: string;
}

/** Group assignment result. */
export interface AdminGroupAssignResponse {
	project: string;
	group: string;
	name?: string;
	agentId: AgentId;
}

/**
 * `nexus admin rename <source> <target>` — admin first-naming/rename for any agent. `source`
 * accepts an agent name, stable `a_*` id, or exact `s_*` session id. `target` is the new globally
 * unique public handle to bind. This is the explicit naming surface for staged identities.
 */
export interface AdminRenameRequest {
	source: string;
	target: string;
}

/**
 * Admin rename result, including the stable target that was changed. `previous = None` means the
 * operation first-named a staged identity.
 */
export interface AdminRenameResponse {
	agentId: AgentId;
	sessionId?: SessionId;
	name: string;
	previous?: string;
}

/** Agent-session access grant role. `viewer` may observe; `coOwner` may observe and delegate. */
export enum AgentAccessRole {
	Viewer = "viewer",
	CoOwner = "coOwner",
}

/**
 * Grant a principal access to a managed agent session.
 *
 * Owners and co-owners may delegate `viewer` or `coOwner` access. The daemon records the grant in
 * its durable ACL table and the gateway `/agent` observe route reads that projection.
 */
export interface AgentAccessGrantRequest {
	/** Stable target managed agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	/** Target managed agent name fallback for callers that do not know the id. */
	name: string;
	/**
	 * Stable principal id receiving access. When present, the daemon resolves this before
	 * `principal` and snapshots the principal's current name.
	 */
	principalAgentId?: AgentId;
	/** Principal name receiving access, or fallback when `principal_agent_id` is omitted. */
	principal: string;
	/** Project scope for the principal. Defaults to the caller's project when omitted. */
	project?: string;
	/** Access role to grant. */
	role: AgentAccessRole;
}

/** Grant result for `agent.grantAccess`. */
export interface AgentAccessGrantResponse {
	name?: string;
	principal: string;
	project: string;
	role: AgentAccessRole;
}

/** Revoke a principal's delegated access to a managed agent session. */
export interface AgentAccessRevokeRequest {
	/** Stable target managed agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	/** Target managed agent name fallback for callers that do not know the id. */
	name: string;
	/**
	 * Stable principal id losing access. When present, the daemon resolves this before
	 * `principal`.
	 */
	principalAgentId?: AgentId;
	/** Principal name losing access, or fallback when `principal_agent_id` is omitted. */
	principal: string;
	/** Project scope for the principal. Defaults to the caller's project when omitted. */
	project?: string;
}

/** Revoke result for `agent.revokeAccess`. */
export interface AgentAccessRevokeResponse {
	name?: string;
	principal: string;
	project: string;
	revoked: boolean;
}

/** `nexus agents create <name>` — create a durable agent identity. */
export interface AgentCreateRequest {
	/** Globally unique display/addressing name for the first implementation pass. */
	name: string;
	/** Default harness used by launch/resume commands when one is not supplied. */
	defaultHarness?: HarnessId;
	/** Project scope the agent belongs to. */
	project?: string;
	/** Operator-facing label; not used for authorization. */
	role?: string;
}

/** Presence state (backend §8). */
export enum Presence {
	Online = "online",
	Busy = "busy",
	Offline = "offline",
}

/** Runtime summary for the current process/session representing a durable agent. */
export interface AgentRuntimeSummary {
	/** The disposable runtime id. In the first pass this is the Nexus `SessionId`. */
	runtimeId: SessionId;
	agentId: AgentId;
	harness: HarnessId;
	cwd?: string;
	transport?: string;
	presence: Presence;
	active: boolean;
	startedAt: number;
	stoppedAt?: number;
	lastHeartbeat?: number;
}

/** One durable agent identity with its current runtime snapshot when available. */
export interface AgentSummary {
	agentId: AgentId;
	/** Public handle. `None` means the identity is staged and not named yet. */
	name?: string;
	project: string;
	defaultHarness?: HarnessId;
	role?: string;
	tier?: string;
	disabled: boolean;
	activeRuntime?: AgentRuntimeSummary;
}

/** Runtime credential creation result. `secret` is returned once. */
export interface AgentCredentialCreateResponse {
	credentialId: CredentialId;
	agentId: AgentId;
	secret: string;
	label?: string;
	purpose?: string;
	scopes: string[];
}

/** Agent creation result. */
export interface AgentCreateResponse {
	agent: AgentSummary;
	/**
	 * Optional first runtime credential. When present, `secret` is shown once and never stored in
	 * plaintext.
	 */
	credential?: AgentCredentialCreateResponse;
}

/** Create a scoped runtime credential for a durable agent. */
export interface AgentCredentialCreateRequest {
	agentId?: AgentId;
	name?: string;
	/** Human-editable label such as "local laptop" or "headed codex". */
	label?: string;
	/** Descriptive only. Authorization uses `scopes`. */
	purpose?: string;
	/** Authorization scopes, e.g. `runtime:register`. */
	scopes: string[];
}

/** Revoke a runtime credential. */
export interface AgentCredentialRevokeRequest {
	credentialId: CredentialId;
}

/** Credential revoke result. */
export interface AgentCredentialRevokeResponse {
	credentialId: CredentialId;
	revoked: boolean;
}

/** List durable agents. */
export interface AgentListRequest {
	project?: string;
	includeDisabled?: boolean;
}

/** Durable agent list response. */
export interface AgentListResponse {
	agents: AgentSummary[];
}

/**
 * Transfer managed agent ownership to another principal.
 *
 * The current owner, or an admin override allowed by the protected-target policy, may replace the
 * `owner_*` fact. Co-owner access grants do not authorize ownership transfer.
 */
export interface AgentOwnerTransferRequest {
	/** Stable target managed agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	/** Target managed agent name fallback for callers that do not know the id. */
	name: string;
	/**
	 * Stable principal id receiving ownership. When present, the daemon resolves this before
	 * `owner` and snapshots the owner's current name/project.
	 */
	ownerAgentId?: AgentId;
	/** Principal name receiving ownership, or fallback when `owner_agent_id` is omitted. */
	owner: string;
	/** Project scope for the new owner. Defaults to the caller's project when omitted. */
	project?: string;
}

/** Transfer result for `agent.transferOwner`. */
export interface AgentOwnerTransferResponse {
	name?: string;
	previousOwner?: string;
	previousProject?: string;
	owner: string;
	project: string;
}

/** List runtimes for one durable agent. */
export interface AgentRuntimeListRequest {
	agentId?: AgentId;
	name?: string;
	includeStopped?: boolean;
}

/** Runtime list response. */
export interface AgentRuntimeListResponse {
	agentId: AgentId;
	runtimes: AgentRuntimeSummary[];
}

/** Show one durable agent by id or name. */
export interface AgentShowRequest {
	agentId?: AgentId;
	name?: string;
}

/** Detailed durable agent response. */
export interface AgentShowResponse {
	agent: AgentSummary;
	runtimes: AgentRuntimeSummary[];
}

/**
 * `nexus thread archive <name>` — hide a thread from active routing/read/search while preserving
 * its registry row and members.
 */
export interface ArchiveThreadRequest {
	name: string;
}

/** `nexus admin assign-project <name> <project>` — set the active project for an agent session. */
export interface AssignProjectRequest {
	/** Stable target agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	name: string;
	project: string;
}

/** Assign-project result. */
export interface AssignProjectResponse {
	name?: string;
	project: string;
}

/** `nexus admin assign-role <name> <role>` — set the registered label (display/addressing only). */
export interface AssignRoleRequest {
	/** Stable target agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	name: string;
	role: string;
}

/** Assign-role result. */
export interface AssignRoleResponse {
	name?: string;
	role: string;
}

/** The shape line the agent sees: `dms=N thread=M total=T` (backend §2.3.1). */
export interface BatchCounts {
	dms: number;
	thread: number;
	total: number;
}

/** Sender/recipient kind. `app` = the human/web client session (backend §4 `sessions.kind`). */
export enum Kind {
	Agent = "agent",
	Human = "human",
	Notification = "notification",
	App = "app",
}

/** Message scope (the one `to` contract resolves into one of these). */
export enum Scope {
	Dm = "dm",
	Thread = "thread",
	Topic = "topic",
}

/**
 * One message in a drop = one `<nexus …>` element. `truncated` marks a preview-capped body
 * (the agent fetches the full body with the MCP `read` tool, or CLI `nexus read <id>`).
 */
export interface BatchMessage {
	id: MessageId;
	from: string;
	kind: Kind;
	scope: Scope;
	/** Thread name (present for thread scope). */
	thread?: string;
	/** Topic name (present for topic scope). */
	topic?: string;
	/** The (possibly preview-truncated) body. */
	body: string;
	/** True when the body was truncated to the preview budget. */
	truncated: boolean;
}

/** Channel op for `nexus admin channel <op> <topic>` (CLI §8). */
export enum ChannelOp {
	Create = "create",
	Delete = "delete",
	SetRoute = "setRoute",
}

/** `nexus admin channel <op> <topic> [--source <s>]` — manage topics / Pub-feed routing. */
export interface ChannelRequest {
	op: ChannelOp;
	topic: string;
	/** Source for `setRoute` (route-by-source). */
	source?: string;
}

/** Compare-and-set revision for one command in a multi-row reorder. */
export interface CommandExpectedRevision {
	commandId: string;
	revision: number;
}

/** Durable lifecycle of one session-composer command. */
export enum CommandQueueState {
	Queued = "queued",
	Claimed = "claimed",
	Started = "started",
	Completed = "completed",
	Failed = "failed",
	Cancelled = "cancelled",
}

/** One command-intent projection for the session queue UI. */
export interface CommandQueueEntry {
	commandId: string;
	clientMessageId?: string;
	sessionId?: string;
	text: string;
	state: CommandQueueState;
	/** `queue` retains the normal turn boundary; `redirect` uses the adapter strategy. */
	mode: string;
	revision: number;
	seq: number;
	createdAt: number;
	claimedAt?: number;
	startedAt?: number;
	completedAt?: number;
	error?: string;
	/** Structured durable error code, never parsed from the display message. */
	errorCode?: number;
	/** Computed by the read authority from the authenticated requester and stored caller. */
	correlationOwned?: boolean;
}

/** Atomic pending-queue mutation selected by the UI. */
export enum CommandQueueAction {
	Cancel = "cancel",
	Edit = "edit",
	Reorder = "reorder",
	RedirectNow = "redirect_now",
}

/** Request for one server-owned queue mutation. Fields not used by the selected action are absent. */
export interface CommandQueueMutationRequest {
	/** Require the existing active runtime to match before a new mutation is applied. */
	expectedSessionId?: SessionId;
	name?: string;
	agentId?: AgentId;
	action: CommandQueueAction;
	clientMutationId: string;
	commandId?: string;
	expectedRevision?: number;
	text?: string;
	commandIds?: string[];
	expectedRevisions?: CommandExpectedRevision[];
}

/** Adapter strategy used for an explicit redirect request. */
export enum SteerCapability {
	/** The adapter can append input to the active turn without interrupting it. */
	NativeSteer = "native_steer",
	/** The adapter atomically interrupts the active turn and starts the durable message next. */
	InterruptAndSend = "interrupt_and_send",
	/** The adapter exposes neither safe strategy. */
	None = "none",
}

/** Result of an atomic queue mutation. */
export interface CommandQueueMutationResponse {
	clientMutationId: string;
	commandId?: string;
	sessionId?: string;
	state: CommandQueueState;
	steerCapability: SteerCapability;
	revision?: number;
	seq: number;
}

/** Immediate durable receipt for a newly queued session command. */
export interface CommandQueueReceipt {
	commandId: string;
	clientMessageId?: string;
	sessionId?: string;
	state: CommandQueueState;
	revision: number;
	seq: number;
}

/** Reconnect snapshot for one daemon-owned session lane. */
export interface CommandQueueSnapshot {
	target: string;
	sessionId?: string;
	/** Derived exclusively from the durable normalized session-turn projection. */
	turnActive: boolean;
	steerCapability: SteerCapability;
	/** Monotonic global queue cursor used as the reconnect `afterSeq` boundary. */
	seq: number;
	/** Queue revision. It advances with `seq`; named separately for compare-and-set UI state. */
	revision: number;
	commands: CommandQueueEntry[];
}

/** One monotonic pushed transition from the durable command-event projection. */
export interface CommandQueueTransition {
	seq: number;
	sessionId?: string;
	commandId: string;
	clientMessageId?: string;
	commandKind: string;
	callerName: string;
	callerSessionId?: string;
	callerAgentId?: AgentId;
	callerPrincipalId?: string;
	callerKind?: string;
	state: CommandQueueState;
	mode: string;
	revision: number;
	correlationOwned?: boolean;
}

/**
 * Trigger NATIVE context compaction on an agent's session by agent name.
 * codex app-server sessions run `thread/compact/start`; headed PTY sessions get
 * the typed `/compact`; transports without a compaction verb error loudly.
 */
export interface CompactRequest {
	/** Dispatch only to this agent's existing active runtime; never revive or retarget. */
	expectedSessionId?: SessionId;
	/** Stable agent target. Omitted session selectors retain legacy revive behavior. */
	agentId?: AgentId;
	/** The target agent's registered name fallback (resolved to its live session). */
	name: string;
	/** Client-generated id used to correlate the terminal command receipt. */
	clientMessageId?: string;
}

/** Response: whether compaction was started (completion streams via observe). */
export interface CompactResponse {
	started: boolean;
	/** Actual resolved dispatch session; not a native lifecycle/admission proof. */
	sessionId?: SessionId;
}

/** `consume` (drain-once) request — the held-receive window for one drain. */
export interface ConsumeRequest {
	/** Held-receive window in ms (None = daemon default). */
	timeoutMs?: number;
	/** Cap on messages drained in one drop (None = DRAIN_LIMIT). */
	max?: number;
}

/** `nexus thread new <name>` — create a named thread, optional initial members. */
export interface CreateThreadRequest {
	name: string;
	members?: string[];
}

/**
 * Where an entity originates. This is deliberately parallel to [`Kind`]: the nature vocabulary
 * remains closed while locality can be carried independently across wire and storage seams.
 */
export enum Locality {
	Local = "local",
	External = "external",
	Trusted = "trusted",
}

/** Privilege tier (overview §5). The human user sits above tiers and is not represented here. */
export enum Tier {
	Agent = "agent",
	Admin = "admin",
}

/**
 * Caller evidence forwarded by a trusted local producer surface.
 *
 * The daemon canonicalizes registered callers from `client_key`; it never treats the optional
 * display name or claimed tier as proof of a registered identity. An env-less local CLI uses the
 * daemon's explicit local-operator sentinel.
 */
export interface DaemonIpcCaller {
	name?: string;
	/**
	 * Descriptive routing scope retained for wire compatibility. It is metadata, not an IPC or
	 * store-partition key.
	 */
	project: string;
	sessionId?: string;
	agentId?: string;
	runtimeId?: string;
	clientKey?: string;
	kind: Kind;
	locality?: Locality;
	access?: string;
	principalId?: string;
	tier: Tier;
}

/** One bounded request frame sent to the daemon-owned local endpoint. */
export interface DaemonIpcRequest {
	version: number;
	/**
	 * Boot-scoped bearer from the mode-0600 endpoint manifest. This rejects stale endpoints and
	 * accidental cross-instance connections; surface authentication still belongs to CLI/gateway.
	 */
	token: string;
	requestId: string;
	caller?: DaemonIpcCaller;
	call: DaemonIpcCall;
}

/** A command-envelope error object. `code` is one of [`codes`]; `data` is optional structured detail. */
export interface RpcError {
	code: number;
	message: string;
	data?: any;
}

/** One response frame. Exactly one of `result` and `error` is present. */
export interface DaemonIpcResponse {
	version: number;
	requestId: string;
	result?: any;
	error?: RpcError;
}

/** `nexus thread delete <name>` — remove a thread registry and its memberships. */
export interface DeleteThreadRequest {
	name: string;
}

/** Developer event classes for [`DeveloperEventEnvelope`]. */
export enum DeveloperEventKind {
	/** A bus message became visible to the target. */
	Message = "message",
	/** A lifecycle/work-state change became visible on the system lifecycle topic. */
	AgentLifecycle = "agent_lifecycle",
	/** A state-changing command action was recorded as metadata-only telemetry. */
	Action = "action",
	/** An observed tool call started or completed on a session-scoped ephemeral topic. */
	ToolCall = "tool_call",
}

/** Tool-call phases for ephemeral `sys.agent.<name>.tool_call` developer events. */
export enum DeveloperToolCallPhase {
	/** The tool call was observed before execution or when it first became visible. */
	Pre = "pre",
	/** The tool call produced a result or terminal status. */
	Post = "post",
}

/**
 * Developer-visible event envelope for the reserved `sys.*` event topics.
 * Durable rows are deliberately metadata-only: they carry enough identity and sequence data for
 * developer tooling, unread counters, and live dashboards, but never include message bodies or
 * turn payloads. Ephemeral tool-call envelopes use the same contract for socket-local,
 * ring-buffered observations and are still observational only; consumers must not feed these
 * events into the agent turn injector.
 */
export interface DeveloperEventEnvelope {
	/**
	 * Event class. Durable values include message, agent lifecycle, and command action events;
	 * `tool_call` is an ephemeral socket-local developer event.
	 */
	kind: DeveloperEventKind;
	/** Reserved topic this envelope was written to, for example `sys.message.thread.nexus-project`. */
	topic: string;
	/** Per-topic monotonic sequence number. */
	seq: number;
	/** Epoch milliseconds when the source event happened. */
	ts: number;
	/** Thread name for thread message events. */
	thread?: string;
	/** Counterparty/display DM name for DM message events. */
	dm?: string;
	/** Display sender for message events. */
	from?: string;
	/** Durable message id for message events. */
	messageId?: MessageId;
	/** Display agent name for lifecycle events. */
	agent?: string;
	/** Runtime/session id for lifecycle events. */
	sessionId?: SessionId;
	/** Lifecycle phase, for example `started`, `stopped`, `turn_end`, `offline`, or `current_work`. */
	lifecycle?: string;
	/** Current-work value when the lifecycle event is about work-state changes. */
	currentWork?: string;
	/** Lifecycle-specific metadata. For example, rename events carry old/new display names. */
	data?: any;
	/** Tool display name for ephemeral tool-call events. */
	tool?: string;
	/** Tool-call phase for ephemeral tool-call events. */
	phase?: DeveloperToolCallPhase;
	/** Whether the post phase finished successfully. `pre` events normally set this to `true`. */
	ok?: boolean;
}

/** One operator-visible dead-letter row. */
export interface DlqEntry {
	inFlightId: string;
	messageId: MessageId;
	sender: string;
	recipientName?: string;
	recipientAgentId?: AgentId;
	recipientSession?: SessionId;
	createdAt: number;
	deadLetteredAt?: number;
	/** Number of completed external harness attempts. Retained across explicit requeues. */
	attemptCount?: number;
	/** Stable machine-readable terminal class used for operator policy. */
	errorCode?: string;
	errorReason?: string;
	/** Structured terminal evidence; retryability is advisory and never triggers daemon replay. */
	errorDetails?: any;
	bodyPreview: string;
}

/** `nexus admin dlq list` — inspect terminal delivery failures without mutating them. */
export interface DlqListRequest {
	/** Agent name, stable `a_*` id, or session `s_*` id. Serialized as `for` for CLI/API parity. */
	for?: string;
	/** Timestamp or duration string accepted by the daemon-side parser. */
	since?: string;
	limit?: number;
}

/** DLQ list response. */
export interface DlqListResponse {
	rows: DlqEntry[];
	total: number;
}

/** DLQ requeue/purge response. */
export interface DlqMutationResponse {
	count: number;
	inFlightIds: string[];
}

/** `nexus admin dlq purge` — explicitly discard dead-letter rows. */
export interface DlqPurgeRequest {
	inFlightId?: string;
	for?: string;
	since?: string;
	yes?: boolean;
}

/** `nexus admin dlq requeue` — move dead-letter rows back to pending. */
export interface DlqRequeueRequest {
	inFlightId?: string;
	for?: string;
	since?: string;
}

/** Hook capability advertised by the local Gateway during stream negotiation. */
export interface GatewayHookCapabilities {
	protocolVersion: number;
	generation: string;
	events: string[];
}

/** Event-specific payload carried by one correlated daemon-to-Gateway evaluation. */
export type HookEvaluationRequest =
	| { event: "before_send", request: HookBeforeSendRequest }
	| { event: "after_receipt", request: HookAfterReceiptRequest };

/** One daemon request on the private correlated hook lane. */
export interface GatewayHookEvaluation {
	correlationId: string;
	request: HookEvaluationRequest;
}

/** Gateway's durable projection watermark for one daemon boot epoch. */
export interface GatewayProjectionAck {
	daemonEpoch: string;
	throughSeq: number;
}

/** Closed set of canonical facts the daemon may project into Gateway persistence. */
export enum GatewayProjectionKind {
	IdentityUpserted = "identity.upserted",
	IdentityRemoved = "identity.removed",
	RuntimeUpserted = "runtime.upserted",
	RuntimeStopped = "runtime.stopped",
	ThreadDeclared = "thread.declared",
	ThreadMembershipChanged = "thread.membership.changed",
	TopicDeclared = "topic.declared",
	TopicSubscriptionChanged = "topic.subscription.changed",
	MessageAccepted = "message.accepted",
	DeliverySettled = "delivery.settled",
	NotificationEmitted = "notification.emitted",
	PresenceChanged = "presence.changed",
}

/**
 * One immutable canonical fact ordered within a volatile daemon boot epoch.
 *
 * `event_id` is the idempotency key and must remain stable if an effect is reclaimed under a new
 * epoch. `daemon_epoch` plus `seq` is only the transport position used for replay and ACKs.
 */
export interface GatewayProjectionEvent {
	eventId: string;
	daemonEpoch: string;
	seq: number;
	occurredAt: number;
	kind: GatewayProjectionKind;
	version: number;
	payload: any;
}

/**
 * `nexus admin grant-tier <name> <agent|admin>` — set an agent's durable privilege tier.
 * This command is intentionally narrower than role assignment: roles are display labels, while
 * tiers are authorization ceilings. Only a human/local admin may grant tiers; agent-admins may use
 * admin capability but may not mint more admins or modify protected human admins.
 */
export interface GrantTierRequest {
	/** Stable target agent id. When present, the daemon resolves this before `name`. */
	agentId?: AgentId;
	name: string;
	tier: Tier;
}

/** Durable tier grant result. */
export interface GrantTierResponse {
	name?: string;
	tier: Tier;
}

/** `POST /heartbeat` — keepalive (sent by the harness loop, not typed). Empty body. */
export interface HeartbeatRequest {
}

/** Heartbeat ack. */
export interface HeartbeatResponse {
	ok: boolean;
}

/** One history line. */
export interface HistoryEntry {
	from: string;
	when: number;
	summary?: string;
	body: string;
}

/** `GET /history` / `nexus history` — chronological recall of a conversation. */
export interface HistoryRequest {
	thread?: string;
	with?: string;
	topic?: string;
	limit?: number;
	/** Only results before this epoch-millis. */
	before?: number;
}

/** History results. */
export interface HistoryResponse {
	entries: HistoryEntry[];
}

/** Authenticated sender identity visible to a hook but immutable in hook output. */
export interface HookSender {
	agentId?: AgentId;
	name: string;
}

/** Canonical message document passed through the hook pipeline. */
export interface HookMessage {
	sender: HookSender;
	target: SendTarget;
	body: string;
	summary?: string;
	mention?: string[];
	metadata?: Record<string, unknown>;
}

/** Compact, signed execution provenance attached by Gateway after validating hook output. */
export interface HookExecutedBy {
	hookId: string;
	entrypoint: string;
	runtime: string;
	artifactDigest: string;
	invocationId: string;
	outcome: string;
	attestation: any;
}

/** Gateway-local invocation after the canonical send receipt exists. */
export interface HookAfterReceiptRequest {
	invocationId: string;
	message: HookMessage;
	receipt: Ack;
	executedBy?: HookExecutedBy[];
}

/** Allowed `after_receipt` output. Message content and timing are immutable at this boundary. */
export interface HookAfterReceiptResult {
	invocationId: string;
	metadata?: Record<string, unknown>;
	executedBy?: HookExecutedBy[];
}

/** Correlated request from the daemon for a new logical send. */
export interface HookBeforeSendRequest {
	evaluationId: string;
	message: HookMessage;
}

/** Terminal pipeline decision. Omitted hook output defaults to continuing the send. */
export enum HookAction {
	Continue = "continue",
	Reject = "reject",
}

/** Public delivery timing selected by a `before_send` hook pipeline. */
export enum DeliveryTiming {
	Interrupt = "interrupt",
	YieldTurn = "yield_turn",
	AfterToolLoop = "after_tool_loop",
}

/** Final Gateway result for one `before_send` evaluation. */
export interface HookBeforeSendResult {
	evaluationId: string;
	action?: HookAction;
	message: HookMessage;
	timing?: DeliveryTiming;
	executedBy?: HookExecutedBy[];
}

/** Structured Gateway-side failure for one correlation ID. */
export interface HookEvaluationFailure {
	code: string;
	message: string;
	retryable?: boolean;
}

/** Register a daemon-tracked durable inbox subscription for the caller. */
export interface InboxSubscribeRequest {
	/** Held-receive window for follow-up `next` calls when no durable batch is ready. */
	timeoutMs?: number;
	/** Cap on messages drained per durable batch (None = DRAIN_LIMIT). */
	max?: number;
}

/** Response for a durable inbox subscription registration. */
export interface InboxSubscribeResponse {
	subscriptionId: string;
	active: boolean;
}

/** Mark a durable subscription batch consumed after the caller has rendered and split-acked it. */
export interface InboxSubscriptionAckRequest {
	subscriptionId: string;
	batchId: string;
}

/**
 * One drain-once drop. `dms`/`threads` are the partitioned previews; the `*MessageIds` mirror
 * them for the split-ack (DMs per-message, threads bulk — backend §2 step 7).
 */
export interface NexusBatch {
	counts: BatchCounts;
	dms: BatchMessage[];
	threads: BatchMessage[];
	dmMessageIds: MessageId[];
	threadMessageIds: MessageId[];
	/** All ids in the drop (dms + threads), for a whole-drop ack. */
	messageIds: MessageId[];
}

/** One durable subscription batch. It must be acknowledged separately from message split-acks. */
export interface InboxSubscriptionBatch {
	batchId: string;
	subscriptionId: string;
	batch: NexusBatch;
}

/** Request the next durable batch for a subscription. */
export interface InboxSubscriptionNextRequest {
	subscriptionId: string;
	/** Optional override for this held receive only. */
	timeoutMs?: number;
}

/** Response for a durable subscription held receive. */
export interface InboxSubscriptionNextResponse {
	batch?: InboxSubscriptionBatch;
}

/** Response for durable subscription ack/unsubscribe operations. */
export interface InboxSubscriptionStatusResponse {
	subscriptionId: string;
	active: boolean;
}

/** Disable a durable inbox subscription. */
export interface InboxUnsubscribeRequest {
	subscriptionId: string;
}

/** Interrupt the active turn on one agent session without injecting replacement text. */
export interface InterruptRequest {
	/** Dispatch only to this agent's existing active runtime; never revive or retarget. */
	expectedSessionId?: SessionId;
	/** The stable target agent id. When present, it is authoritative over `name`. */
	agentId?: AgentId;
	/** The target agent's registered name fallback. */
	name: string;
	/** Client-generated id used to correlate the terminal command receipt. */
	clientMessageId?: string;
}

/** Response emitted only after the adapter accepted the interrupt. */
export interface InterruptResponse {
	interrupted: boolean;
	/** Actual runtime binding selected by the router. */
	sessionId?: SessionId;
}

/** `nexus thread join <name>` (caller joins). */
export interface JoinThreadRequest {
	name: string;
}

/** `nexus thread leave <name>` (caller leaves). */
export interface LeaveThreadRequest {
	name: string;
}

/** `nexus members` request. */
export interface MemberListRequest {
	/**
	 * Optional directory metadata filter. `None` returns the global directory; projects never
	 * act as a routing or authorization boundary.
	 */
	project?: string;
	/** Include offline members (default false). */
	includeOffline?: boolean;
	/** Include dead-marked members (default false; audit/admin views only). */
	includeDead?: boolean;
}

/** One entry in the `nexus members` directory (CLI §3). */
export interface MemberSummary {
	/** Durable identity for this member. `None` only for legacy rows not yet backfilled. */
	agentId?: AgentId;
	name?: string;
	/**
	 * The session this member is bound to. Lets the web console address an exact daemon-owned
	 * session as `/agent/<name>:<session_id>` (the operator's view onto that harness) instead of
	 * by name alone — disambiguating across renames / name reuse.
	 */
	sessionId: SessionId;
	/** The harness/runtime label (`claude`/`codex`/…); `None` for human/app sessions. */
	agent?: string;
	/** Entity origin, independent of its closed nature. Legacy rows default to local. */
	locality?: Locality;
	/** Provider or policy-defined access label. */
	access?: string;
	role?: string;
	presence: Presence;
	currentWork?: string;
	/**
	 * Durable lifecycle: `None`/absent = active; `Some("dead")` = unrevivable/unreachable.
	 * This remains separate from `presence`, which is transport truth.
	 */
	lifecycleState?: string;
	/**
	 * Why the row was marked dead (`revive_exhausted` | `no_resume_id` |
	 * `transport_unreachable` | `operator_fossil_sweep`).
	 */
	deadReason?: string;
}

/** `GET /members` / `nexus members` response. */
export interface MemberListResponse {
	members: MemberSummary[];
}

/**
 * Cryptographic, verifiable sender stamp stored on every message (backend §1).
 * Not injected in-band; queryable for UI/audit/dispute.
 */
export interface ProvenanceStamp {
	/** Signature algorithm, e.g. "ed25519". */
	algo: string;
	/** Base64/hex signature over the canonical message bytes. */
	signature: string;
	/** Unix epoch millis when the stamp was produced. */
	signedAt: number;
}

/** Provenance: the in-band tag attributes + the optional stored crypto stamp. */
export interface Provenance {
	/** Sender name (the `from` attr of `<nexus …>`). */
	from: string;
	/** `agent` | `human` | `notification` (the `kind` attr). */
	kind: Kind;
	/** Entity origin, independent of its closed nature. Legacy messages default to local. */
	locality?: Locality;
	/** Provider or policy-defined access label. */
	access?: string;
	/** Thread NAME (omitted for DMs) — the `thread` attr. */
	thread?: string;
	/** Topic name for pub/sub — the `topic` attr. */
	topic?: string;
	/** Stored crypto stamp (audit only; never in-band). `None` until stamped. */
	stamp?: ProvenanceStamp;
}

/** The canonical, immutable message record (one per send, even on fan-out). */
export interface Message {
	id: MessageId;
	project: ProjectId;
	/** Sender name (`messages.from_name`). */
	from: string;
	scope: Scope;
	/** Resolved internal thread id (hidden from agents; present for thread scope). */
	thread?: ThreadId;
	/** Resolved topic id (present for topic scope). */
	topic?: TopicId;
	body: string;
	summary?: string;
	provenance: Provenance;
	/** Unix epoch millis. */
	createdAt: number;
}

/** Idempotent recursive metadata merge produced by one completed hook invocation. */
export interface MessageMetadataMergeRequest {
	messageId: MessageId;
	invocationId: string;
	metadata: Record<string, unknown>;
}

/** Core entity families that support an opaque metadata JSON bag. */
export enum MetadataEntityKind {
	Message = "message",
	Session = "session",
	Thread = "thread",
	Agent = "agent",
}

/** Read request for one entity metadata bag. */
export interface MetadataGetRequest {
	entity: MetadataEntityKind;
	id: string;
}

/** Metadata response for REST and command-intent callers. */
export interface MetadataResponse {
	entity: MetadataEntityKind;
	id: string;
	metadata: any;
}

/** Set/replace the metadata bag for one project-scoped entity. */
export interface MetadataSetRequest {
	entity: MetadataEntityKind;
	/** Entity id. For threads and agents this may be the public name; messages/sessions use ids. */
	id: string;
	/** Opaque JSON payload. Nexus stores and returns it without interpreting its shape. */
	metadata: any;
}

/** `nexus admin monitor` — stream the web console event feed for oversight. */
export interface MonitorRequest {
	follow: boolean;
	scope?: string;
}

/**
 * A command-envelope notification: the internal event shape (no `id`). `params` carries a
 * [`crate::events::WsEvent`]; `method` is the dotted event name (e.g. `"message.created"`).
 */
export interface Notification {
	/** Always `"2.0"` ([`JSONRPC_VERSION`]). */
	jsonrpc: string;
	/** The dotted event name (the `WsEvent` `type`). */
	method: string;
	/** The event body — deserialize into the matching `WsEvent` variant. */
	params?: any;
}

/**
 * Durable command-intent envelope produced only after the public gateway verifies a notification.
 *
 * The daemon deliberately stores and re-verifies the exact signed bytes instead of trusting a
 * caller-supplied Boolean. `timestamp` remains a string so signature verification never rewrites
 * the producer's bytes. The worker parses `raw_body` into [`NotifyRequest`] only after verification.
 */
export interface NotifyCommandRequest {
	rawBody: string;
	timestamp: string;
	signature: string;
}

/** `POST /notify` body. `payload` is the opaque producer JSON (stored, rendered to subscribers). */
export interface NotifyRequest {
	/** Producer source label (CI, GitHub, cron, …). */
	source: string;
	/** Optional topic; absent → Pub feed only (no agent path). */
	topic?: string;
	/** Opaque producer payload. */
	payload: any;
}

/** Ingest result. `notifId` is the id of the ingested `notification`-kind message. */
export interface NotifyResponse {
	notifId: MessageId;
	/** Resolved recipients at ingest (recorded for the web console audit). */
	routedTo: string[];
	/** Whether the HMAC verified. */
	hmacOk: boolean;
}

/**
 * Daemon-owned one-shot notification command. The body is stored once and recipient delivery
 * state is derived inside the daemon. `source` is attribution, never authentication.
 */
export interface NotifySendRequest {
	target: NotifyTarget;
	source?: string;
	body: string;
	idempotencyKey?: string;
}

/** A project scope label exposed for compatibility with older clients. */
export interface Project {
	projectId: ProjectId;
	/** Unique human-readable scope label. */
	name: string;
	/**
	 * Compatibility metadata when a caller can provide a creator; not backed by
	 * a durable project primitive.
	 */
	createdBy: string;
	/** Optional cwd/repo hint for legacy clients. */
	rootPath?: string;
	/** Unix epoch millis. */
	createdAt: number;
}

/** Inject one operator message directly into an agent's ACP session by agent name. */
export interface PromptRequest {
	/** Dispatch only to this agent's existing active runtime; never revive or retarget. */
	expectedSessionId?: SessionId;
	/**
	 * Stable target identity, authoritative over `name`. Only legacy omission of
	 * `expectedSessionId` permits revival.
	 */
	agentId?: AgentId;
	/** The target agent's registered name fallback (resolved to its live ACP session). */
	name: string;
	/** The operator's message text (injected as a `session/prompt` turn). */
	text: string;
	/**
	 * Optional client-generated message id for reconciling the optimistic web echo
	 * with the streamed `user_input` event.
	 */
	clientMessageId?: string;
}

/** Response: whether the turn was injected (the reply itself streams over the WS). */
export interface PromptResponse {
	delivered: boolean;
	/** Actual runtime binding used by the router, not a native delivery receipt. */
	sessionId?: SessionId;
}

/**
 * `POST /push` body. Sent by an authenticated source to push an event onto the bus.
 * The source token is carried via [`SOURCE_SIGNATURE_HEADER`]; it is NOT a JSON field.
 */
export interface PushRequest {
	/** Name of the registered source making the push. */
	source: string;
	/** Override topic for this push; absent → source's default topic. */
	topic?: string;
	/** Short human-readable summary (used as notification title). */
	summary?: string;
	/** Full event body (rendered to subscribers). */
	body: string;
	/** Opaque producer metadata (stored, not interpreted by the bus). */
	meta?: any;
}

/** Receipt for a committed source push. Fan-out means queued recipient rows, not model delivery. */
export interface PushResponse {
	/** The resolved topic the push was routed to. */
	topic: string;
	/** Canonical message id, absent only when the topic has no subscribers and no message is made. */
	messageId?: MessageId;
	/** Number of committed recipient delivery rows. This does not claim harness completion. */
	queuedTo: number;
}

/**
 * `read` request — fetch a full message by id (used to pull a truncated batch body,
 * backend §2.3.1; returns the full `Message`).
 */
export interface ReadRequest {
	id: MessageId;
}

/**
 * Compatibility request for older clients that still present a project label
 * creation flow.
 */
export interface RegisterProjectRequest {
	name: string;
	rootPath?: string;
}

/** Response: a compatibility project label record. */
export interface RegisterProjectResponse {
	project: Project;
}

/** `POST /register` / `nexus register` payload. Idempotent on `clientKey`. */
export interface RegisterRequest {
	/**
	 * Unique name to bind (one name = one session).
	 * Public handle. `None` means the identity is staged and not named yet.
	 */
	name?: string;
	/**
	 * Durable agent identity to bind this runtime to. Omitted by legacy callers, which are
	 * resolved by `(project, name)` plus `clientKey` compatibility.
	 */
	agentId?: AgentId;
	harness: HarnessId;
	/** The harness's own session id (bound to `name`). */
	harnessSessionId: string;
	/**
	 * Project label (from cwd or explicit) — descriptive metadata, never an identity or routing
	 * boundary.
	 */
	project: string;
	/** Stable per-harness-session key; resume reuses the session on a known key. */
	clientKey: string;
	/**
	 * Runtime credential secret proving this process may register as `agentId`. Omitted by legacy
	 * callers during the compatibility window.
	 */
	runtimeCredential?: string;
	tier: Tier;
	/** `agent` | `app` (defaults to agent server-side if omitted). */
	kind?: Kind;
	/** Entity origin, independent of its closed nature. Legacy callers default to local. */
	locality?: Locality;
	/** Provider or policy-defined access label. */
	access?: string;
	/** Registered label (display/addressing only). */
	role?: string;
	cwd?: string;
}

/** `RegisterResponse`: the bound session id + the `<nexus>` startup directive. */
export interface RegisterResponse {
	/**
	 * Durable identity this runtime is bound to. Legacy implementations may omit this until the
	 * identity/runtime migration is active.
	 */
	agentId?: AgentId;
	/** The session id the agent's identity is bound to (never typed again). */
	sessionId: SessionId;
	/** The startup directive: "untagged = your human, `<nexus>` = the bus." */
	directive: string;
}

/**
 * `nexus admin remove <name>` — tear down a session's loop (message store retained).
 * `kill=true` additionally terminates the spawned harness OS process; `kill=false` (default)
 * is the old evict-only behaviour and keeps backward compatibility for callers that omit the
 * field.
 */
export interface RemoveRequest {
	/**
	 * Stable target agent id carried for id-capable clients. When present, `admin.remove` and
	 * `admin.delete` select the target session by this id; `name` is the legacy selector when the id
	 * is omitted.
	 */
	agentId?: AgentId;
	name: string;
	/**
	 * When `true`, the spawned harness process is SIGKILL-ed in addition to the session being
	 * detached. Defaults to `false` so existing callers (no field) continue to work.
	 */
	kill?: boolean;
}

/** Remove result. */
export interface RemoveResponse {
	name?: string;
	status: string;
}

/**
 * `nexus rename <new>` / MCP `rename` — the caller changes its OWN display name (an agent renames
 * himself). The new name must be free in the caller's project.
 */
export interface RenameRequest {
	/** The new name to bind to the caller's session. */
	name: string;
}

/** Result of a self-rename: the new name and the one it replaced. */
export interface RenameResponse {
	name: string;
	/**
	 * `None` means the caller was a staged (unnamed) identity that just claimed its first
	 * name through self-service first-naming, provided the name is free.
	 */
	previous?: string;
}

/**
 * `nexus thread rename <name> <new-name>` — rename a thread by its stable registry row, preserving
 * memberships and message history.
 */
export interface RenameThreadRequest {
	name: string;
	newName: string;
}

/**
 * A command-envelope request. `params` is method-specific (see the registry); deserialize it into the
 * registry's concrete type after reading `method`. An absent `id` means **notification
 * semantics on the request side** (a fire-and-forget call expecting no response) — for the
 * internal push/event shape use [`Notification`].
 */
export interface Request {
	/** Always `"2.0"` ([`JSONRPC_VERSION`]). */
	jsonrpc: string;
	/** Correlates the response. Absent = notification semantics (no response expected). */
	id?: RequestId;
	/** The method name (a key in the Nexus method registry). */
	method: string;
	/** Method params — deserialize into the registry type for `method`. */
	params?: any;
}

/**
 * A command-envelope response. **Exactly one** of `result` / `error` is set; the unused one is
 * omitted from the wire via `skip_serializing_if`. `result` is the registry's result type for the
 * request's `method`.
 */
export interface Response {
	/** Always `"2.0"` ([`JSONRPC_VERSION`]). */
	jsonrpc: string;
	/** Echoes the request id (`None` only for a response to an id-less request — rare). */
	id?: RequestId;
	/** The success payload — the registry result type for the method. Mutually exclusive with `error`. */
	result?: any;
	/** The failure object. Mutually exclusive with `result`. */
	error?: RpcError;
}

/** `nexus admin route <notif> --to <name|thread>` — ad-hoc, one-shot forward (NOT a standing rule). */
export interface RouteForwardRequest {
	/** The notification message id to forward. */
	notif: MessageId;
	/** Recipient: an agent name or thread name. */
	to: string;
}

/**
 * A standing route rule (by source and/or topic) → a recipient name or thread.
 * Reused by admin `channel set-route` (CLI §8). At least one of `source`/`topic` is set.
 */
export interface RouteRule {
	source?: string;
	topic?: string;
	/** Recipient: an agent name or a thread name. */
	to: string;
}

/** One search hit. */
export interface SearchHit {
	messageId: MessageId;
	from: string;
	/** Epoch millis. */
	when: number;
	snippet: string;
	score: number;
}

/** Search engine selector (CLI §7 `--semantic|--fts|--hybrid`). */
export enum SearchMode {
	Fts = "fts",
	Semantic = "semantic",
	Hybrid = "hybrid",
}

/** `GET /search` / `nexus search <query>`. */
export interface SearchRequest {
	query: string;
	mode: SearchMode;
	limit?: number;
	/** Restrict to a thread by name. */
	thread?: string;
	/** Restrict to a DM partner by name. */
	with?: string;
	/** Only results at/after this epoch-millis. */
	since?: number;
}

/** Search results. */
export interface SearchResponse {
	hits: SearchHit[];
}

/**
 * A send request. `summary` is the optional short index line; `mention` is a soft highlight
 * inside a thread (not a routing change). `idempotency_key` is scoped by the daemon to the
 * sender session so a retry returns the original [`Ack`] without creating another message.
 */
export interface SendRequest {
	to: SendTarget;
	summary?: string;
	body: string;
	mention?: string[];
	/** Developer-owned metadata that is committed atomically with the message body. */
	metadata?: Record<string, unknown>;
	idempotencyKey?: string;
}

/** A registered notification source. */
export interface Source {
	/** Unique human-readable name for this source (e.g. `"github-ci"`). */
	name: string;
	/** Default topic pushes from this source are routed to. */
	topic: string;
	/** Whether the source is currently active. */
	enabled: boolean;
	/** Unix milliseconds when the source was registered. */
	createdAt: number;
	/** Unix milliseconds of the most recent successful push; absent if never fired. */
	lastFiredAt?: number;
}

/** Response body for `"source.list"`. */
export interface SourceListResponse {
	sources: Source[];
}

/** A minimal source reference used by show / enable / disable / rotate / remove operations. */
export interface SourceRef {
	name: string;
}

/** Request payload for the `"source.register"` method/command. Registers a new notification source. */
export interface SourceRegisterRequest {
	/** Desired name for the source — must be unique within the workspace. */
	name: string;
	/** Override the default topic; absent → daemon assigns a default. */
	topic?: string;
}

/** Result of a successful `"source.register"` call. `token` is returned in plaintext once. */
export interface SourceRegisterResponse {
	/** The newly-created source record. */
	source: Source;
	/** Plaintext bearer token — shown once; store it securely. */
	token: string;
}

/** Response body for `"source.rotate"` — returns the new token in plaintext, once. */
export interface SourceTokenResponse {
	name: string;
	token: string;
}

/** `nexus admin spawn <kind>` — admin-initiated spawn (the agent still self-registers). */
export enum SpawnIdentityPolicy {
	/** No explicit identity was supplied; resume should prefer an existing native owner. */
	Implicit = "implicit",
	/** The request name was supplied by the caller and should be treated as intentional. */
	ExplicitName = "explicitName",
	/** The request name is an explicit stable `a_*` agent id. */
	ExplicitAgentId = "explicitAgentId",
}

export interface SpawnRequest {
	kind: HarnessId;
	name?: string;
	/** Whether `name` was caller-supplied identity intent or generated/implicit launch metadata. */
	identityPolicy?: SpawnIdentityPolicy;
	cwd?: string;
	project?: string;
	role?: string;
	/**
	 * Fresh-launch model-visible boot prompt template. The daemon expands `<var.*>` after
	 * allocating identity/runtime and rejects this field for resume/reuse paths.
	 */
	initialPrompt?: string;
	/**
	 * Harness-native resume key. For headed Codex app-server launches this is the Codex thread id
	 * used to start `codex resume --remote ... <thread>`. Defaults to `None` for older callers and
	 * fresh launches.
	 */
	resume?: string;
	/**
	 * Harness-native argv tail from `nexus launch <harness> [args...]`. The daemon passes these to
	 * headed harness launches after applying harness-specific normalization in the CLI. Defaults to
	 * an empty vector so older callers keep launching fresh sessions.
	 */
	harnessArgs?: string[];
	/**
	 * When `true`, the agent is spawned headlessly via the daemon's ACP runner (no TUI/PTY).
	 * Defaults to `false` so existing callers that omit the field continue to work.
	 */
	headless?: boolean;
	/**
	 * Local terminal backend for headed launches: `"pty"` (raw daemon-owned PTY) or `"tmux"`
	 * (multiplexer-owned; survives daemon restarts). `None` resolves via
	 * [`SpawnRequest::resolved_backend`]: the operator's configured default
	 * (`launch_backend` in `nexus.toml` / `NEXUS_LAUNCH_BACKEND`), else `"pty"`.
	 * Hermes always resolves to `"tmux"` — its gateway bridge is
	 * welded to the tmux viewer profile.
	 */
	backend?: string;
}

/** Spawn result. */
export interface SpawnResponse {
	sessionId: SessionId;
}

/** The self-set state for `nexus status` (CLI §6). `paused` is a self-pause hold. */
export enum StatusState {
	Active = "active",
	Busy = "busy",
	Paused = "paused",
}

/** `POST /status` / `nexus status`. No fields set = show current status. */
export interface StatusRequest {
	state?: StatusState;
	work?: string;
}

/** Status echo. */
export interface StatusResponse {
	presence: Presence;
	currentWork?: string;
	paused: boolean;
}

/**
 * Redirect one durable operator message into the active turn. This is deliberately separate from
 * [`PromptRequest`]: normal prompts retain the daemon's
 * per-session `harness.prompt` boundary queue. Redirects use the target adapter's declared
 * capability: native steering when available, otherwise an adapter-owned interrupt-and-send.
 */
export interface SteerRequest {
	/** Dispatch only to this agent's existing active runtime; never revive or retarget. */
	expectedSessionId?: SessionId;
	/**
	 * Stable target identity, authoritative over `name`. Only legacy omission of
	 * `expectedSessionId` permits revival.
	 */
	agentId?: AgentId;
	/** The target agent's registered name fallback. */
	name: string;
	/** Additional operator input for the active turn. */
	text: string;
	/** Client-generated id used for optimistic-row reconciliation and command idempotency. */
	clientMessageId?: string;
}

/** Delivery decision for an explicit redirect request. */
export enum SteerDelivery {
	/** A native-steer adapter accepted the input into the active regular turn. */
	Steered = "steered",
	/**
	 * Legacy decode-only value from releases that converted a stale steer into `turn/start`.
	 *
	 * Nexus no longer emits this value: the frontend owns the turn/steer choice, so a missing
	 * active turn is rejected with [`crate::codes::ACTIVE_TURN_REQUIRED`].
	 */
	FallbackStarted = "fallback_started",
	/** A non-native adapter interrupted the prior turn and accepted this message as the next turn. */
	InterruptedAndStarted = "interrupted_and_started",
}

/** Response returned only after the selected adapter accepts the redirect operation. */
export interface SteerResponse {
	/** Actual runtime binding selected by the router. */
	sessionId?: SessionId;
	accepted: boolean;
	delivery: SteerDelivery;
	turnId?: string;
}

/** `nexus subscribe <topic>` — `group` = competing-consumer group. */
export interface SubscribeRequest {
	topic: string;
	group?: string;
}

/** Subscribe result: the topic + the cursor the subscriber resumes from. */
export interface SubscribeResponse {
	topic: string;
	cursor: number;
}

/** One member row in a channel-open header read. */
export interface ThreadHeaderMember {
	name: string;
	kind?: string;
	agent?: string;
	presence: string;
	sessionId: string;
	currentWork?: string;
}

/** `GET /api/v1/threads/:name/header` — the compact read needed to open a channel. */
export interface ThreadHeaderResponse {
	name: string;
	topic?: string;
	description?: string;
	/** Unix epoch millis of the last message, if any. */
	lastAt?: number;
	members: ThreadHeaderMember[];
	memberCount: number;
	activeSessions: number;
}

/** One thread in a list (`nexus threads`). Name + members + last activity. */
export interface ThreadSummary {
	name: string;
	topic?: string;
	description?: string;
	members: string[];
	/** Unix epoch millis of the last message, if any. */
	lastAt?: number;
	/**
	 * Latest metadata-only developer event sequence for `sys.message.thread.<name>`.
	 * Consumers can keep a per-thread last-seen sequence and compare it with this value for
	 * unread counters without replaying message bodies.
	 */
	latestSeq?: number;
}

/** `GET /threads` / `nexus threads` response. */
export interface ThreadListResponse {
	threads: ThreadSummary[];
}

/**
 * Add/remove a SPECIFIC member to/from an existing thread (`thread.addMember` /
 * `thread.removeMember`) — the operator managing a channel's roster, distinct from `thread.join`
 * which only adds the caller itself.
 */
export interface ThreadMemberRequest {
	name: string;
	member: string;
}

/** `nexus thread members <name>` request. */
export interface ThreadMembersRequest {
	name: string;
}

/** Members of one thread. */
export interface ThreadMembersResponse {
	name: string;
	members: string[];
}

/**
 * Canonical `agent.update` payload for `kind: "tool_call"` — C-TOOL v1
 * (docs/tool-call-contract.md). PRODUCER LAW: every harness adapter fills `tool` with the machine
 * tool name and `input` with the structured args object whenever the harness exposes them.
 * `title` is display-only and may be a command line; consumers must never treat it as identity.
 */
export interface ToolCallData {
	/** Merge key across the call's phases (START/ARGS/RESULT). */
	id: string;
	/**
	 * Machine tool name: `shell`, `read`, `write`, `edit`, `search`, `fetch`, or the harness's
	 * registered tool name (`Bash`, `Write`, …). NEVER a human title or command line.
	 */
	tool: string;
	/** Human display label (an ACP title; may be a command line). */
	title?: string;
	/** ACP tool kind (`read`/`edit`/`execute`/`search`/…) when known. */
	kind?: string;
	status?: string;
	/** Structured arguments — a JSON object/array, NEVER a pre-stringified JSON string. */
	input?: any;
	output?: any;
	locations?: any;
}

/** One topic in a list (`nexus topics`). */
export interface TopicSummary {
	topic: string;
	subscribers: number;
}

/** `GET /topics` / `nexus topics` response. */
export interface TopicListResponse {
	topics: TopicSummary[];
}

/** `nexus unsubscribe <topic>`. */
export interface UnsubscribeRequest {
	topic: string;
}

/**
 * Pre-warm an agent's ACP session WITHOUT sending a prompt — the AionUi "spawn at
 * conversation-open" move. Called when the web console opens a DM pane (the `observe`
 * subscribe), so the harness subprocess is spawned + the session opened/resumed AHEAD of the
 * operator's first message. Without this the first DM pays the full cold-start
 * (`npx` + ACP `initialize` + `session/new`) synchronously — the "huge send latency".
 */
export interface WarmRequest {
	/** The stable target agent id. When present, the daemon revives this id before `name`. */
	agentId?: AgentId;
	/** The target agent's registered name fallback (resolved + brought live). */
	name: string;
}

/** Response: whether the session is now live (spawned/resumed and ready for `prompt`). */
export interface WarmResponse {
	warm: boolean;
}

/** `GET /whoami` / `nexus whoami` — the caller's resolved bound identity. */
export interface Whoami {
	/** Durable identity. `None` only for legacy rows not yet backfilled. */
	agentId?: AgentId;
	/** Public handle. `None` means the identity is staged and not named yet. */
	name?: string;
	sessionId: SessionId;
	role?: string;
	tier: Tier;
	project: string;
	presence: Presence;
}

/**
 * What kind of ACP activity an `agent.update` carries — 1:1 with the renderable ACP
 * `session/update` variants the daemon forwards (the full-stream pass-through). The UI interprets
 * the loosely-typed `data` payload per `kind`.
 *
 * snake_case on the wire: `text` / `thinking` / `tool_call` / `plan` / `commands`.
 */
export enum AgentUpdateKind {
	/** A streamed chunk of the agent's reply text (`AgentMessageChunk`). `data`: `{"text": …}`. */
	Text = "text",
	/** A streamed chunk of the agent's internal reasoning (`AgentThoughtChunk`). `data`: `{"text": …}`. */
	Thinking = "thinking",
	/**
	 * A tool call started or updated (`ToolCall` / `ToolCallUpdate`). `data`: a [`ToolCallData`]
	 * value (C-TOOL v1, docs/tool-call-contract.md); the UI merges successive updates by `id`.
	 */
	ToolCall = "tool_call",
	/** The agent's execution plan (`Plan`). `data`: `{"entries": […]}`. */
	Plan = "plan",
	/**
	 * The harness's own advertised slash commands (`AvailableCommandsUpdate`). `data`:
	 * `{"commands": [{name, description}, …]}`.
	 */
	Commands = "commands",
	/**
	 * A user-role turn the harness received, echoed back by ACP as `UserMessageChunk`. `data`:
	 * `{"text": …}`. This is the operator's own typed input (or a daemon-injected `<nexus-batch>`
	 * turn) — surfacing it makes the web `/agent/<name>:<session_id>` view and the `nexus attach`
	 * TUI mirror each other: what you type on one shows on both, because it rides the SAME ACP
	 * session stream. Faithful to "what the harness saw."
	 */
	UserInput = "user_input",
	/**
	 * Turn complete — the harness emitted its terminal boundary (for example ACP
	 * `session/prompt` returned `StopReason`, Codex emitted `turn/completed`, or OpenCode reported
	 * `session.idle`). Direct/legacy ACP display paths may infer this UI lifecycle marker from
	 * stream quiescence, but durable bus settlement never treats silence as completion evidence.
	 * Carries no content (`data`: `{}`); the gateway maps it to AG-UI `RUN_FINISHED` so the web
	 * console can close the streaming row.
	 */
	TurnEnd = "turn_end",
}

/** Per-recipient delivery state machine (backend §2.1 / §4 `in_flight.state`). */
export enum DeliveryState {
	Pending = "pending",
	Notified = "notified",
	Delivered = "delivered",
	Acked = "acked",
}

/** Event-specific terminal result returned by Gateway. */
export type HookEvaluationResponse =
	| { event: "before_send", result: HookBeforeSendResult }
	| { event: "after_receipt", result: HookAfterReceiptResult };


// --- Hand-authored wire unions (appended by gen-ts.sh / the ts_gen test) ---
//
// typeshare 1.13 cannot emit internally-tagged (`#[serde(tag = ...)]`) algebraic enums or infer
// untagged-enum unions, so the three serde unions below are authored to match the frozen Rust wire
// shape exactly (the same JSON the crate's round-trip tests + golden fixtures assert). The Rust
// types reference these via `#[typeshare(serialized_as = "...")]`. Keep in lockstep with
// `src/send.rs` (SendTarget), `src/notify.rs` (NotifyTarget), `src/daemon_ipc.rs`
// (DaemonIpcCall), `src/events.rs` (WsEvent), and `src/rpc.rs` (RequestId).

// String-backed id newtypes (src/ids.rs). They are `#[serde(transparent)]` and defined via a
// macro, so typeshare's parser does not see the definitions (it only sees the usages); we emit the
// `= string` aliases here. The wire shape is a bare JSON string.
export type SessionId = string;
export type AgentId = string;
export type CredentialId = string;
export type MessageId = string;
export type ThreadId = string;
export type TopicId = string;
export type ProjectId = string;

/** JSON-RPC request id — a bare number or string ([`RequestId`], `#[serde(untagged)]`). */
export type RequestIdWire = number | string;

/** The send target/verb — internally tagged by `verb` ([`SendTarget`]). */
export type SendTargetWire =
	| { verb: "dm"; name?: string; agentId?: AgentId }
	| { verb: "post"; thread: string }
	| { verb: "publish"; topic: string }
	| { verb: "reply" };

/** Explicit one-shot notification target — internally tagged by `kind` ([`NotifyTarget`]). */
export type NotifyTargetWire =
	| { kind: "auto"; value: string }
	| { kind: "agent"; agentId: AgentId }
	| { kind: "name"; name: string }
	| { kind: "group"; group: string }
	| { kind: "thread"; thread: string };

/** One daemon IPC operation — internally tagged by `mode` ([`DaemonIpcCall`]). */
export type DaemonIpcCallWire =
	| { mode: "command"; commandId: string; kind: string; params: unknown; idempotencyKey?: string }
	| { mode: "enqueue"; commandId: string; kind: string; params: unknown; idempotencyKey?: string }
	| { mode: "query"; method: string; params: unknown };

/** The daemon event stream — internally tagged by `type` ([`WsEvent`]). */
export type WsEventWire =
	| { type: "message.created"; messageId: MessageId }
	| { type: "message.delivered"; messageId: MessageId; recipient: SessionId }
	| { type: "agent.update"; sessionId: SessionId; kind: "text" | "thinking" | "tool_call" | "plan" | "commands" | "turn_end" | "user_input"; data: unknown }
	| { type: "agent.status"; sessionId: SessionId; presence: Presence; paused: boolean }
	| { type: "agent.spawned"; sessionId: SessionId; name: string; agentId?: string | null }
	| { type: "agent.removed"; sessionId: SessionId; name: string }
	| { type: "thread.created"; thread: string; members: string[] }
	| { type: "thread.member.changed"; thread: string; members: string[] }
	| { type: "topic.published"; topic: string; messageId: MessageId }
	| { type: "notification.received"; notifId: MessageId; routedTo: string[] }
	| { type: "developer.event"; event: DeveloperEventEnvelope };
