// Contract DTOs from the generated mirror. Server routes and UI modules consume
// these shapes from one place. `verbatimModuleSyntax` is on, so these are pure
// `export type`.
//
// NEVER redefine a contract DTO here — re-export only.
export type {
  // --- JSON-RPC envelope ---
  Request,
  Response,
  RpcError,
  RequestId,
  RequestIdWire,
  Notification,

  // --- method request/response DTOs (one pair per registry method) ---
  RegisterRequest,
  RegisterResponse,
  RegisterProjectRequest,
  RegisterProjectResponse,
  SendRequest,
  SendTarget,
  SendTargetWire,
  Ack,
  ReadRequest,
  ConsumeRequest,
  AckRequest,
  AckResponse,
  AckThreadsRequest,
  MemberListRequest,
  MemberListResponse,
  CreateThreadRequest,
  JoinThreadRequest,
  LeaveThreadRequest,
  ThreadMembersRequest,
  ThreadMembersResponse,
  ThreadListResponse,
  SubscribeRequest,
  SubscribeResponse,
  UnsubscribeRequest,
  TopicListResponse,
  StatusRequest,
  StatusResponse,
  HeartbeatRequest,
  HeartbeatResponse,
  SearchRequest,
  SearchResponse,
  HistoryRequest,
  HistoryResponse,
  NotifyRequest,
  NotifyResponse,
  RouteRule,
  RouteForwardRequest,
  SpawnRequest,
  SpawnResponse,
  RemoveRequest,
  RemoveResponse,
  AssignRoleRequest,
  AssignRoleResponse,
  ChannelRequest,
  MonitorRequest,
} from "./contracts.gen";
