// ────────────────────────────────────────────────────────────────────────────
// GENERATED BY drizzle-kit pull — DO NOT EDIT.
//
// This file mirrors the Rust-owned Turso schema (the `nexus` daemon is the SOLE
// writer; see core/migrations/0001_init.sql). It is the introspected read view:
// in production it is regenerated with `pnpm db:pull` (drizzle-kit pull) against
// the live Turso; until then it is hand-authored to match the migration DDL
// EXACTLY (column names + SQLite affinities), which is the documented
// contract-first path — "seeded in-memory libSQL introspected identically to
// Turso". Never `drizzle-kit generate`/`migrate` from here; never the source of
// truth for a migration.
//
// These tables describe DB ROWS for display. They are a SEPARATE layer from the
// generated contract wire types (`@shared/types`); do not conflate the two.
// ────────────────────────────────────────────────────────────────────────────
import {
  sqliteTable,
  text,
  integer,
  primaryKey,
} from "drizzle-orm/sqlite-core";

// identity: register-once; one name = one harness session. Names are GLOBALLY unique.
export const sessions = sqliteTable("sessions", {
  sessionId: text("session_id").primaryKey(),
  name: text("name"),
  agent: text("agent"), // 'claude'|'codex'|'app'
  kind: text("kind"), // 'agent'|'app'(human/web)
  role: text("role"), // registered label (display)
  tier: text("tier").default("agent"), // 'agent'|'admin'
  harnessSessionId: text("harness_session_id"),
  clientKey: text("client_key"),
  cwd: text("cwd"),
  project: text("project"),
  currentWork: text("current_work"),
  presence: text("presence"), // 'online'|'busy'|'offline'
  paused: integer("paused").default(0),
  pausedBy: text("paused_by"),
  callbackUrl: text("callback_url"),
  lastHeartbeat: integer("last_heartbeat"),
  createdAt: integer("created_at"),
  metadataJson: text("metadata_json"),
  // Durable agent identity this session belongs to (agents.agent_id). The
  // live DB has carried this column since staged identities; regeneration
  // emits it too — clients must NEVER derive an agent id from session_id
  // (an agent's later sessions keep the FIRST session's a_* id).
  agentId: text("agent_id"),
});

// durable agent identity registry (stable identity, separate from live runtime rows).
export const agents = sqliteTable("agents", {
  agentId: text("agent_id").primaryKey(),
  project: text("project"),
  name: text("name"),
  defaultHarness: text("default_harness"),
  role: text("role"),
  tier: text("tier").default("agent"),
  disabledAt: integer("disabled_at"),
  createdAt: integer("created_at"),
  metadataJson: text("metadata_json"),
  ownerName: text("owner_name"),
  ownerProject: text("owner_project"),
  ownerSessionId: text("owner_session_id"),
  ownerAgentId: text("owner_agent_id"),
});

export const agentCredentials = sqliteTable("agent_credentials", {
  credentialId: text("credential_id").primaryKey(),
  agentId: text("agent_id"),
  secretHash: text("secret_hash"),
  purpose: text("purpose"),
  label: text("label"),
  scopesJson: text("scopes_json"),
  metadataJson: text("metadata_json"),
  revokedAt: integer("revoked_at"),
  lastUsedAt: integer("last_used_at"),
  createdAt: integer("created_at"),
});

export const agentRuntimes = sqliteTable("agent_runtimes", {
  runtimeId: text("runtime_id").primaryKey(),
  agentId: text("agent_id"),
  harness: text("harness"),
  cwd: text("cwd"),
  transport: text("transport"),
  presence: text("presence"),
  active: integer("active").default(1),
  startedAt: integer("started_at"),
  stoppedAt: integer("stopped_at"),
  lastHeartbeat: integer("last_heartbeat"),
});

export const agentAclGrants = sqliteTable(
  "agent_acl_grants",
  {
    agentId: text("agent_id"),
    principalProject: text("principal_project"),
    principalName: text("principal_name"),
    principalSessionId: text("principal_session_id"),
    principalAgentId: text("principal_agent_id"),
    role: text("role"),
    grantedByName: text("granted_by_name"),
    grantedByProject: text("granted_by_project"),
    createdAt: integer("created_at"),
    updatedAt: integer("updated_at"),
  },
  (t) => [primaryKey({ columns: [t.agentId, t.principalProject, t.principalName] })],
);

// canonical immutable message record (one per send, even on fan-out).
export const messages = sqliteTable("messages", {
  messageId: text("message_id").primaryKey(),
  fromName: text("from_name"),
  kind: text("kind"), // 'dm'|'thread'|'topic'|'notification'
  toName: text("to_name"), // agent name OR thread name OR topic
  threadId: text("thread_id"), // resolved internal id (hidden from agents)
  topic: text("topic"),
  summary: text("summary"),
  body: text("body"),
  provenance: text("provenance"), // stored provenance JSON
  project: text("project"), // project scope (every read is project-scoped)
  createdAt: integer("created_at"),
  fromAgentId: text("from_agent_id"),
  toAgentId: text("to_agent_id"),
  metadataJson: text("metadata_json"),
});

// per-recipient delivery state machine (the in_flight / transient queue).
export const inFlight = sqliteTable("in_flight", {
  inFlightId: text("in_flight_id").primaryKey(),
  messageId: text("message_id"), // FK -> messages.message_id
  recipientSession: text("recipient_session"), // FK -> sessions.session_id
  state: text("state").default("pending"), // pending|notified|delivered|acked
  deliveredAt: integer("delivered_at"),
  ackedAt: integer("acked_at"),
});

// threads: named, ids hidden from agents.
export const threads = sqliteTable("threads", {
  threadId: text("thread_id").primaryKey(),
  name: text("name"),
  project: text("project"),
  topic: text("topic"),
  description: text("description"),
  createdBy: text("created_by"),
  createdAt: integer("created_at"),
  archivedAt: integer("archived_at"),
  metadataJson: text("metadata_json"),
});

export const threadMembers = sqliteTable(
  "thread_members",
  {
    threadId: text("thread_id"),
    sessionName: text("session_name"),
    joinedAt: integer("joined_at"),
  },
  (t) => [primaryKey({ columns: [t.threadId, t.sessionName] })],
);

// topics / pub-sub.
export const topics = sqliteTable("topics", {
  topic: text("topic").primaryKey(),
  project: text("project"),
  createdAt: integer("created_at"),
});

export const subscriptions = sqliteTable(
  "subscriptions",
  {
    topic: text("topic"),
    subscriberSession: text("subscriber_session"),
    subGroup: text("sub_group"), // group = competing-consumer
    cursor: integer("cursor").default(0),
    subscribedAt: integer("subscribed_at"),
  },
  (t) => [primaryKey({ columns: [t.topic, t.subscriberSession] })],
);

// notifications push-in routing audit (who-gets-what).
export const notifications = sqliteTable("notifications", {
  notifId: text("notif_id").primaryKey(),
  source: text("source"),
  topic: text("topic"),
  hmacOk: integer("hmac_ok"),
  payload: text("payload"),
  routedTo: text("routed_to"), // resolved recipients (csv) at ingest
  createdAt: integer("created_at"),
});

// metadata-only developer event topic cursors.
export const developerEventTopics = sqliteTable("developer_event_topics", {
  topic: text("topic").primaryKey(),
  latestSeq: integer("latest_seq").default(0),
  updatedAt: integer("updated_at"),
});

// metadata-only developer event envelopes; no message bodies are stored here.
export const developerEvents = sqliteTable("developer_events", {
  topic: text("topic"),
  seq: integer("seq"),
  kind: text("kind"),
  messageId: text("message_id"),
  threadName: text("thread_name"),
  dmName: text("dm_name"),
  fromName: text("from_name"),
  agentName: text("agent_name"),
  sessionId: text("session_id"),
  lifecycle: text("lifecycle"),
  currentWork: text("current_work"),
  dataJson: text("data_json"),
  createdAt: integer("created_at"),
});

// daemon-owned ingress queue for producer commands; gateway writes intents, daemon executes them.
export const commandIntents = sqliteTable("command_intents", {
  commandId: text("command_id").primaryKey(),
  kind: text("kind"),
  status: text("status"),
  project: text("project"),
  callerName: text("caller_name"),
  callerSessionId: text("caller_session_id"),
  callerAgentId: text("caller_agent_id"),
  callerRuntimeId: text("caller_runtime_id"),
  callerClientKey: text("caller_client_key"),
  callerKind: text("caller_kind"),
  callerTier: text("caller_tier"),
  idempotencyKey: text("idempotency_key"),
  requestJson: text("request_json"),
  resultJson: text("result_json"),
  errorJson: text("error_json"),
  attempts: integer("attempts").default(0),
  createdAt: integer("created_at"),
  claimedAt: integer("claimed_at"),
  leaseUntil: integer("lease_until"),
  completedAt: integer("completed_at"),
});

// notification sources. The daemon owns registration/rotation; the gateway read
// path uses the token only to verify signed producer pushes before enqueueing a
// `source.push` command intent.
export const sources = sqliteTable("sources", {
  name: text("name").primaryKey(),
  token: text("token"),
  topic: text("topic"),
  enabled: integer("enabled").default(1),
  createdAt: integer("created_at"),
  lastFiredAt: integer("last_fired_at"),
});

// routing_rules: standing route rules (by source and/or topic) → a recipient
// name or thread. Display-only projection used by the web console `listRoutingRules`
// (the daemon owns the authoritative routing config; this is the read shape).
export const routingRules = sqliteTable("routing_rules", {
  ruleId: text("rule_id").primaryKey(),
  source: text("source"),
  topic: text("topic"),
  toName: text("to_name"), // recipient: agent name or thread name
  project: text("project"),
  createdAt: integer("created_at"),
});

// Note: the FTS5 virtual table (`messages_fts`) is not modeled as a Drizzle table —
// search is issued as a raw SELECT through the read client (Drizzle has no FTS5
// builder).

// The full introspected schema object, passed to drizzle(client, { schema }).
export const schema = {
  sessions,
  agents,
  agentCredentials,
  agentRuntimes,
  messages,
  inFlight,
  threads,
  threadMembers,
  topics,
  subscriptions,
  notifications,
  developerEventTopics,
  developerEvents,
  commandIntents,
  sources,
  routingRules,
};
