import { createRouter } from "@tanstack/react-router";

// Generated by the TanStack Start / Router Vite plugin from `src/routes/*`.
import { routeTree } from "./routeTree.gen";

export function createAppRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: "intent",
  });
}

// TanStack Start convention: export a `getRouter` factory the runtime calls.
export const getRouter = createAppRouter;

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof createAppRouter>;
  }
}
