/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PubRouteImport } from './routes/pub'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmAgentRouteImport } from './routes/dm.$agent'
import { Route as CChannelRouteImport } from './routes/c.$channel'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiAguiRouteImport } from './routes/api/agui'
import { Route as AgentHandleRouteImport } from './routes/agent.$handle'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiProjectsAssignRouteImport } from './routes/api/projects.assign'
import { Route as ApiConversationSteerRouteImport } from './routes/api/conversation.steer'
import { Route as ApiConversationPromptRouteImport } from './routes/api/conversation.prompt'
import { Route as ApiConversationMessagesRouteImport } from './routes/api/conversation.messages'
import { Route as ApiConversationLogsRouteImport } from './routes/api/conversation.logs'
import { Route as ApiConversationInterruptRouteImport } from './routes/api/conversation.interrupt'
import { Route as ApiConversationCompactRouteImport } from './routes/api/conversation.compact'
import { Route as ApiAguiObserveRouteImport } from './routes/api/agui.observe'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PubRoute = PubRouteImport.update({
  id: '/pub',
  path: '/pub',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmAgentRoute = DmAgentRouteImport.update({
  id: '/dm/$agent',
  path: '/dm/$agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CChannelRoute = CChannelRouteImport.update({
  id: '/c/$channel',
  path: '/c/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAguiRoute = ApiAguiRouteImport.update({
  id: '/api/agui',
  path: '/api/agui',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHandleRoute = AgentHandleRouteImport.update({
  id: '/agent/$handle',
  path: '/agent/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsAssignRoute = ApiProjectsAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiConversationSteerRoute = ApiConversationSteerRouteImport.update({
  id: '/api/conversation/steer',
  path: '/api/conversation/steer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationPromptRoute = ApiConversationPromptRouteImport.update({
  id: '/api/conversation/prompt',
  path: '/api/conversation/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationMessagesRoute = ApiConversationMessagesRouteImport.update({
  id: '/api/conversation/messages',
  path: '/api/conversation/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationLogsRoute = ApiConversationLogsRouteImport.update({
  id: '/api/conversation/logs',
  path: '/api/conversation/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationInterruptRoute =
  ApiConversationInterruptRouteImport.update({
    id: '/api/conversation/interrupt',
    path: '/api/conversation/interrupt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationCompactRoute = ApiConversationCompactRouteImport.update({
  id: '/api/conversation/compact',
  path: '/api/conversation/compact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAguiObserveRoute = ApiAguiObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => ApiAguiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/pub': typeof PubRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/agent/$handle': typeof AgentHandleRoute
  '/api/agui': typeof ApiAguiRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/c/$channel': typeof CChannelRoute
  '/dm/$agent': typeof DmAgentRoute
  '/api/agui/observe': typeof ApiAguiObserveRoute
  '/api/conversation/compact': typeof ApiConversationCompactRoute
  '/api/conversation/interrupt': typeof ApiConversationInterruptRoute
  '/api/conversation/logs': typeof ApiConversationLogsRoute
  '/api/conversation/messages': typeof ApiConversationMessagesRoute
  '/api/conversation/prompt': typeof ApiConversationPromptRoute
  '/api/conversation/steer': typeof ApiConversationSteerRoute
  '/api/projects/assign': typeof ApiProjectsAssignRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/pub': typeof PubRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/agent/$handle': typeof AgentHandleRoute
  '/api/agui': typeof ApiAguiRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/c/$channel': typeof CChannelRoute
  '/dm/$agent': typeof DmAgentRoute
  '/api/agui/observe': typeof ApiAguiObserveRoute
  '/api/conversation/compact': typeof ApiConversationCompactRoute
  '/api/conversation/interrupt': typeof ApiConversationInterruptRoute
  '/api/conversation/logs': typeof ApiConversationLogsRoute
  '/api/conversation/messages': typeof ApiConversationMessagesRoute
  '/api/conversation/prompt': typeof ApiConversationPromptRoute
  '/api/conversation/steer': typeof ApiConversationSteerRoute
  '/api/projects/assign': typeof ApiProjectsAssignRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/pub': typeof PubRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/agent/$handle': typeof AgentHandleRoute
  '/api/agui': typeof ApiAguiRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/c/$channel': typeof CChannelRoute
  '/dm/$agent': typeof DmAgentRoute
  '/api/agui/observe': typeof ApiAguiObserveRoute
  '/api/conversation/compact': typeof ApiConversationCompactRoute
  '/api/conversation/interrupt': typeof ApiConversationInterruptRoute
  '/api/conversation/logs': typeof ApiConversationLogsRoute
  '/api/conversation/messages': typeof ApiConversationMessagesRoute
  '/api/conversation/prompt': typeof ApiConversationPromptRoute
  '/api/conversation/steer': typeof ApiConversationSteerRoute
  '/api/projects/assign': typeof ApiProjectsAssignRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/members'
    | '/pub'
    | '/search'
    | '/sources'
    | '/agent/$handle'
    | '/api/agui'
    | '/api/login'
    | '/api/mcp'
    | '/api/projects'
    | '/c/$channel'
    | '/dm/$agent'
    | '/api/agui/observe'
    | '/api/conversation/compact'
    | '/api/conversation/interrupt'
    | '/api/conversation/logs'
    | '/api/conversation/messages'
    | '/api/conversation/prompt'
    | '/api/conversation/steer'
    | '/api/projects/assign'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/members'
    | '/pub'
    | '/search'
    | '/sources'
    | '/agent/$handle'
    | '/api/agui'
    | '/api/login'
    | '/api/mcp'
    | '/api/projects'
    | '/c/$channel'
    | '/dm/$agent'
    | '/api/agui/observe'
    | '/api/conversation/compact'
    | '/api/conversation/interrupt'
    | '/api/conversation/logs'
    | '/api/conversation/messages'
    | '/api/conversation/prompt'
    | '/api/conversation/steer'
    | '/api/projects/assign'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/members'
    | '/pub'
    | '/search'
    | '/sources'
    | '/agent/$handle'
    | '/api/agui'
    | '/api/login'
    | '/api/mcp'
    | '/api/projects'
    | '/c/$channel'
    | '/dm/$agent'
    | '/api/agui/observe'
    | '/api/conversation/compact'
    | '/api/conversation/interrupt'
    | '/api/conversation/logs'
    | '/api/conversation/messages'
    | '/api/conversation/prompt'
    | '/api/conversation/steer'
    | '/api/projects/assign'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  PubRoute: typeof PubRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  AgentHandleRoute: typeof AgentHandleRoute
  ApiAguiRoute: typeof ApiAguiRouteWithChildren
  ApiLoginRoute: typeof ApiLoginRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  CChannelRoute: typeof CChannelRoute
  DmAgentRoute: typeof DmAgentRoute
  ApiConversationCompactRoute: typeof ApiConversationCompactRoute
  ApiConversationInterruptRoute: typeof ApiConversationInterruptRoute
  ApiConversationLogsRoute: typeof ApiConversationLogsRoute
  ApiConversationMessagesRoute: typeof ApiConversationMessagesRoute
  ApiConversationPromptRoute: typeof ApiConversationPromptRoute
  ApiConversationSteerRoute: typeof ApiConversationSteerRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pub': {
      id: '/pub'
      path: '/pub'
      fullPath: '/pub'
      preLoaderRoute: typeof PubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$agent': {
      id: '/dm/$agent'
      path: '/dm/$agent'
      fullPath: '/dm/$agent'
      preLoaderRoute: typeof DmAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$channel': {
      id: '/c/$channel'
      path: '/c/$channel'
      fullPath: '/c/$channel'
      preLoaderRoute: typeof CChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agui': {
      id: '/api/agui'
      path: '/api/agui'
      fullPath: '/api/agui'
      preLoaderRoute: typeof ApiAguiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$handle': {
      id: '/agent/$handle'
      path: '/agent/$handle'
      fullPath: '/agent/$handle'
      preLoaderRoute: typeof AgentHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/assign': {
      id: '/api/projects/assign'
      path: '/assign'
      fullPath: '/api/projects/assign'
      preLoaderRoute: typeof ApiProjectsAssignRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/conversation/steer': {
      id: '/api/conversation/steer'
      path: '/api/conversation/steer'
      fullPath: '/api/conversation/steer'
      preLoaderRoute: typeof ApiConversationSteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/prompt': {
      id: '/api/conversation/prompt'
      path: '/api/conversation/prompt'
      fullPath: '/api/conversation/prompt'
      preLoaderRoute: typeof ApiConversationPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/messages': {
      id: '/api/conversation/messages'
      path: '/api/conversation/messages'
      fullPath: '/api/conversation/messages'
      preLoaderRoute: typeof ApiConversationMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/logs': {
      id: '/api/conversation/logs'
      path: '/api/conversation/logs'
      fullPath: '/api/conversation/logs'
      preLoaderRoute: typeof ApiConversationLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/interrupt': {
      id: '/api/conversation/interrupt'
      path: '/api/conversation/interrupt'
      fullPath: '/api/conversation/interrupt'
      preLoaderRoute: typeof ApiConversationInterruptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/compact': {
      id: '/api/conversation/compact'
      path: '/api/conversation/compact'
      fullPath: '/api/conversation/compact'
      preLoaderRoute: typeof ApiConversationCompactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agui/observe': {
      id: '/api/agui/observe'
      path: '/observe'
      fullPath: '/api/agui/observe'
      preLoaderRoute: typeof ApiAguiObserveRouteImport
      parentRoute: typeof ApiAguiRoute
    }
  }
}

interface ApiAguiRouteChildren {
  ApiAguiObserveRoute: typeof ApiAguiObserveRoute
}

const ApiAguiRouteChildren: ApiAguiRouteChildren = {
  ApiAguiObserveRoute: ApiAguiObserveRoute,
}

const ApiAguiRouteWithChildren =
  ApiAguiRoute._addFileChildren(ApiAguiRouteChildren)

interface ApiProjectsRouteChildren {
  ApiProjectsAssignRoute: typeof ApiProjectsAssignRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsAssignRoute: ApiProjectsAssignRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  PubRoute: PubRoute,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  AgentHandleRoute: AgentHandleRoute,
  ApiAguiRoute: ApiAguiRouteWithChildren,
  ApiLoginRoute: ApiLoginRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  CChannelRoute: CChannelRoute,
  DmAgentRoute: DmAgentRoute,
  ApiConversationCompactRoute: ApiConversationCompactRoute,
  ApiConversationInterruptRoute: ApiConversationInterruptRoute,
  ApiConversationLogsRoute: ApiConversationLogsRoute,
  ApiConversationMessagesRoute: ApiConversationMessagesRoute,
  ApiConversationPromptRoute: ApiConversationPromptRoute,
  ApiConversationSteerRoute: ApiConversationSteerRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
